version: "3"
services:
  spring-app:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: prod  # Default profile jika tidak ditentukan
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbprod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar"]  # Jalankan Spring Boot dalam mode production
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db-prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbprod
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data-prod:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data-prod:
