version: "3"
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE : default  # Default profile jika tidak ditentukan
      SPRING_DATASOURCE_URL : jdbc:mysql://db:3306/db_test
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : root
      SPRING_JPA_HIBERNATE_DDL_AUTO : update
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data-dev:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data-dev:
